version: '3.7'

services:

  mysqlmaster1:
    image: mysql:5.7.27
    ports:
      - 13301:3306
    networks:
      - haproxy-mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./mysql/master1:/etc/mysql/conf.d/
      # https://hub.docker.com/_/mysql
      # Furthermore, it will execute files with extensions .sh, .sql and .sql.gz
      # that are found in /docker-entrypoint-initdb.d.
      # Files will be executed in alphabetical order.
      - ./mysql/init1.sql:/docker-entrypoint-initdb.d/init.sql

  mysqlmaster2:
    image: mysql:5.7.27
    ports:
      - '13302:3306'
    networks:
      - haproxy-mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./mysql/master2:/etc/mysql/conf.d/
      - ./mysql/init2.sql:/docker-entrypoint-initdb.d/init.sql

  ha1:
    image: haproxy:1.7.11-alpine
    ports:
      - 13303:3306
      - 13304:9999
    networks:
      - haproxy-mysql
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro

networks:
  haproxy-mysql:
    name: haproxy-mysql